version: "3.3"
services:
  webapi:
    container_name: lucas_case_app
    restart: always
    build:
      context: .
    ports:
      - "8088:8088"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_HOST: db
      POSTGRES_DATABASE: postgres
    depends_on:
      - db
    networks:
      - simple-transfer-case
  worker:
    container_name: lucas_case_worker
    restart: always
    build:
      dockerfile: Dockerfile-worker
      context: .
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_HOST: db
      POSTGRES_DATABASE: postgres
    depends_on:
      - db
    networks:
      - simple-transfer-case
  db:
    container_name: lucas_case_db
    image: kartoza/postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - lucas_case_db_vol:/var/lib/postgresql/data
    networks:
      - simple-transfer-case

networks:
  simple-transfer-case:
    driver: bridge

volumes:
  lucas_case_db_vol:
