version: "3.3"
services:
  webapi:
    container_name: lucas_case_app
    restart: always
    build:
      context: .
    ports:
      - "8088:8088"
    environment:
      CONF_POSTGRES_PASSWORD: postgres
      CONF_POSTGRES_USERNAME: postgres
      CONF_POSTGRES_HOST: db
      CONF_POSTGRES_DATABASE: postgres
      CONF_APP_ENV: running
    depends_on:
      - db
    networks:
      - simple-transfer-case
  worker:
    container_name: lucas_case_worker
    restart: always
    build:
      dockerfile: Dockerfile-worker
      context: .
    environment:
      CONF_POSTGRES_PASSWORD: postgres
      CONF_POSTGRES_USERNAME: postgres
      CONF_POSTGRES_HOST: db
      CONF_POSTGRES_DATABASE: postgres
      CONF_APP_ENV: running
      CONF_AUTHORIZER_URL: https://run.mocky.io/v3/8fafdd68-a090-496f-8c9a-3442cf30dae6
      CONF_NOTIFIER_URL: http://o4d9z.mocklab.io/notify
    depends_on:
      - db
    networks:
      - simple-transfer-case
  db:
    container_name: lucas_case_db
    image: kartoza/postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - lucas_case_db_vol:/var/lib/postgresql/data
    networks:
      - simple-transfer-case

networks:
  simple-transfer-case:
    driver: bridge

volumes:
  lucas_case_db_vol:
